"""
PDF report generator using ReportLab.
Bloomberg Analyst Desk aesthetic: dark navy header, clean serif body,
financial metrics table, color-coded thesis sections.
"""
import io
import re
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    HRFlowable,
    KeepTogether,
)
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

# ── Brand colors ────────────────────────────────────────────────────────────
NAVY = colors.HexColor("#0D1B2A")
ACCENT = colors.HexColor("#1A6B9A")
GOLD = colors.HexColor("#C9A84C")
LIGHT_GRAY = colors.HexColor("#F5F6F8")
MID_GRAY = colors.HexColor("#8A95A3")
TEXT = colors.HexColor("#1C2530")
GREEN = colors.HexColor("#1D7A4F")
RED = colors.HexColor("#B0291D")
WHITE = colors.white


# ── Page header/footer ───────────────────────────────────────────────────────
def _on_page(canvas, doc):
    canvas.saveState()
    w, h = letter

    # Header bar
    canvas.setFillColor(NAVY)
    canvas.rect(0, h - 0.55 * inch, w, 0.55 * inch, fill=1, stroke=0)
    canvas.setFillColor(WHITE)
    canvas.setFont("Helvetica-Bold", 9)
    canvas.drawString(0.5 * inch, h - 0.35 * inch, "ALPHAFLOW  ·  EQUITY RESEARCH")
    canvas.setFont("Helvetica", 8)
    canvas.drawRightString(w - 0.5 * inch, h - 0.35 * inch,
                           "INSTITUTIONAL USE ONLY  ·  NOT FOR REDISTRIBUTION")

    # Gold accent line under header
    canvas.setStrokeColor(GOLD)
    canvas.setLineWidth(1.5)
    canvas.line(0, h - 0.56 * inch, w, h - 0.56 * inch)

    # Footer
    canvas.setFillColor(MID_GRAY)
    canvas.setFont("Helvetica", 7.5)
    today = datetime.today().strftime("%B %d, %Y")
    canvas.drawString(0.5 * inch, 0.35 * inch,
                      f"Generated by AlphaFlow AI Research  ·  {today}")
    canvas.drawCentredString(w / 2, 0.35 * inch, f"Page {doc.page}")
    canvas.drawRightString(w - 0.5 * inch, 0.35 * inch,
                           "This report is AI-generated and does not constitute financial advice.")

    canvas.setStrokeColor(LIGHT_GRAY)
    canvas.setLineWidth(0.5)
    canvas.line(0.5 * inch, 0.55 * inch, w - 0.5 * inch, 0.55 * inch)
    canvas.restoreState()


# ── Styles ────────────────────────────────────────────────────────────────────
def _build_styles():
    s = getSampleStyleSheet()
    base = dict(fontName="Helvetica", textColor=TEXT, leading=14)

    styles = {
        "company_name": ParagraphStyle("company_name", fontName="Helvetica-Bold",
                                       fontSize=22, textColor=NAVY, leading=26, spaceAfter=4),
        "report_title": ParagraphStyle("report_title", fontName="Helvetica",
                                       fontSize=13, textColor=ACCENT, leading=16, spaceAfter=2),
        "meta": ParagraphStyle("meta", fontName="Helvetica", fontSize=8,
                               textColor=MID_GRAY, leading=11, spaceAfter=12),
        "section_header": ParagraphStyle("section_header", fontName="Helvetica-Bold",
                                          fontSize=10, textColor=WHITE, leading=14,
                                          spaceBefore=14, spaceAfter=6,
                                          leftIndent=-6, rightIndent=-6,
                                          backColor=NAVY),
        "subsection": ParagraphStyle("subsection", fontName="Helvetica-Bold",
                                      fontSize=9.5, textColor=ACCENT, leading=13,
                                      spaceBefore=8, spaceAfter=4),
        "body": ParagraphStyle("body", **base, fontSize=9, alignment=TA_JUSTIFY,
                                spaceAfter=6),
        "bullet": ParagraphStyle("bullet", **base, fontSize=9, leftIndent=12,
                                  bulletIndent=0, spaceAfter=3),
        "metric_label": ParagraphStyle("metric_label", fontName="Helvetica",
                                        fontSize=8.5, textColor=MID_GRAY, leading=11),
        "metric_value": ParagraphStyle("metric_value", fontName="Helvetica-Bold",
                                        fontSize=10, textColor=NAVY, leading=13),
        "disclaimer": ParagraphStyle("disclaimer", fontName="Helvetica",
                                      fontSize=7, textColor=MID_GRAY, leading=10,
                                      alignment=TA_CENTER),
    }
    return styles


# ── Helpers ───────────────────────────────────────────────────────────────────
def _fmt_m(v):
    """Format millions → $XB or $XM."""
    if v is None:
        return "N/A"
    v = float(v)
    if abs(v) >= 1000:
        return f"${v/1000:.2f}B"
    return f"${v:.0f}M"


def _fmt_pct(v, plus=True):
    if v is None:
        return "N/A"
    sign = "+" if (plus and v > 0) else ""
    return f"{sign}{v:.1f}%"


def _pct_color(v):
    if v is None:
        return TEXT
    return GREEN if v >= 0 else RED


def _section_block(title: str, styles: dict):
    """Navy background section header."""
    return [
        Spacer(1, 6),
        Paragraph(f"  {title.upper()}", styles["section_header"]),
    ]


def _parse_memo_sections(memo_text: str) -> list[tuple[str, str]]:
    """Split memo markdown into (heading, body) pairs."""
    sections = []
    current_title = ""
    current_body = []

    for line in memo_text.split("\n"):
        if line.startswith("## "):
            if current_title or current_body:
                sections.append((current_title, "\n".join(current_body).strip()))
            current_title = line[3:].strip()
            current_body = []
        else:
            current_body.append(line)

    if current_title or current_body:
        sections.append((current_title, "\n".join(current_body).strip()))

    return sections


def _body_paragraphs(text: str, styles: dict) -> list:
    """Convert markdown text to ReportLab flowables."""
    flowables = []
    for line in text.split("\n"):
        line = line.strip()
        if not line:
            flowables.append(Spacer(1, 3))
        elif line.startswith("**") and line.endswith("**"):
            flowables.append(Paragraph(
                f"<b>{line[2:-2]}</b>", styles["subsection"]
            ))
        elif re.match(r"^\*\*(.+?):\*\*", line):
            label, _, rest = line[2:].partition(":**")
            flowables.append(Paragraph(
                f"<b>{label}:</b>{rest}", styles["body"]
            ))
        elif line.startswith("- ") or line.startswith("• "):
            flowables.append(Paragraph(
                f"• {line[2:]}", styles["bullet"]
            ))
        else:
            # Strip leftover ** markers
            line = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", line)
            flowables.append(Paragraph(line, styles["body"]))
    return flowables


# ── Main PDF builder ──────────────────────────────────────────────────────────
def generate_pdf(company_data: dict, metrics: dict, tone: dict, memo: str) -> bytes:
    buf = io.BytesIO()
    doc = BaseDocTemplate(
        buf,
        pagesize=letter,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
        leftMargin=0.65 * inch,
        rightMargin=0.65 * inch,
    )

    frame = Frame(
        doc.leftMargin, doc.bottomMargin,
        doc.width, doc.height,
        id="main",
    )
    doc.addPageTemplates([PageTemplate(id="main", frames=frame, onPage=_on_page)])

    styles = _build_styles()
    co = company_data["company"]
    fin = company_data["financials"]
    ctx = company_data["context"]
    story = []

    # ── Cover block ──────────────────────────────────────────────────────────
    story.append(Spacer(1, 10))
    story.append(Paragraph(co["name"], styles["company_name"]))
    story.append(Paragraph(
        f"{co['ticker']}  ·  {co['sector']}  ·  {fin['quarter']} Earnings Analysis",
        styles["report_title"]
    ))
    story.append(Paragraph(
        f"Period ended {fin['period_end']}  ·  Market Cap: ${co['market_cap_b']}B  "
        f"·  Employees: {co['employees']:,}",
        styles["meta"]
    ))
    story.append(HRFlowable(width="100%", thickness=2, color=GOLD, spaceAfter=10))

    # ── Quick KPI strip ──────────────────────────────────────────────────────
    kpi_data = [
        ["REVENUE", "GROSS MARGIN", "OPERATING MARGIN", "EPS (DILUTED)", "FREE CASH FLOW"],
        [
            _fmt_m(fin["revenue_m"]),
            _fmt_pct(fin["gross_margin_pct"], plus=False),
            _fmt_pct(fin["operating_margin_pct"], plus=False),
            f"${fin['eps_diluted']:.2f}",
            _fmt_m(fin["free_cash_flow_m"]),
        ],
        [
            _fmt_pct(fin["revenue_growth_yoy_pct"]) + " YoY",
            _fmt_pct(fin["gross_margin_pct"] - fin["gross_margin_prev_year_pct"]) + " YoY",
            "",
            _fmt_pct(fin["eps_growth_yoy_pct"]) + " YoY",
            "",
        ],
    ]
    kpi_style = TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 7),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("FONTNAME", (0, 1), (-1, 1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 1), (-1, 1), 13),
        ("TEXTCOLOR", (0, 1), (-1, 1), NAVY),
        ("FONTNAME", (0, 2), (-1, 2), "Helvetica"),
        ("FONTSIZE", (0, 2), (-1, 2), 8),
        ("TEXTCOLOR", (0, 2), (-1, 2), GREEN),
        ("BACKGROUND", (0, 1), (-1, -1), LIGHT_GRAY),
        ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#D0D5DC")),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
    ])
    kpi_table = Table(kpi_data, colWidths=[doc.width / 5] * 5)
    kpi_table.setStyle(kpi_style)
    story.append(kpi_table)
    story.append(Spacer(1, 8))

    # Tone badge
    tone_colors = {"bullish": GREEN, "neutral": ACCENT, "cautious": GOLD, "bearish": RED}
    tc = tone_colors.get(tone.get("overall_tone", "neutral"), ACCENT)
    story.append(Paragraph(
        f"Management Tone: <b><font color='#{tc.hexval()[2:]}'>"
        f"{tone.get('overall_tone','N/A').upper()}</font></b>  ·  "
        f"Confidence: {tone.get('confidence_score','N/A')}/10  ·  "
        f"Beat Revenue by {_fmt_pct(fin['consensus'].get('beat_revenue_pct'))}  ·  "
        f"Beat EPS by {_fmt_pct(fin['consensus'].get('beat_eps_pct'))}",
        styles["meta"]
    ))

    # ── Segment table ────────────────────────────────────────────────────────
    if fin.get("segments"):
        story += _section_block("Revenue Breakdown by Segment", styles)
        seg_rows = [["SEGMENT", "REVENUE", "YoY GROWTH"]]
        for seg in fin["segments"]:
            seg_rows.append([
                seg["name"],
                _fmt_m(seg["revenue_m"]),
                _fmt_pct(seg["growth_yoy_pct"]),
            ])
        seg_style = TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), ACCENT),
            ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8.5),
            ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
            ("ALIGN", (0, 0), (0, -1), "LEFT"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, LIGHT_GRAY]),
            ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#D0D5DC")),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ])
        seg_table = Table(seg_rows, colWidths=[doc.width * 0.5, doc.width * 0.25, doc.width * 0.25])
        seg_table.setStyle(seg_style)
        story.append(seg_table)

    # ── Guidance box ─────────────────────────────────────────────────────────
    guidance = fin.get("guidance", {})
    story += _section_block("Management Guidance", styles)
    g_data = [
        ["METRIC", "GUIDANCE"],
        ["Next Quarter Revenue", guidance.get("revenue_range", "N/A")],
        ["Gross Margin", guidance.get("gross_margin_guidance", "N/A")],
    ]
    g_style = TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), ACCENT),
        ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, LIGHT_GRAY]),
        ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#D0D5DC")),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ])
    g_table = Table(g_data, colWidths=[doc.width * 0.35, doc.width * 0.65])
    g_table.setStyle(g_style)
    story.append(g_table)
    story.append(Spacer(1, 4))
    story.append(Paragraph(
        f"<i>{guidance.get('management_commentary', '')}</i>",
        styles["body"]
    ))

    # ── Memo sections ────────────────────────────────────────────────────────
    sections = _parse_memo_sections(memo)
    for title, body in sections:
        if not title:
            continue
        story += _section_block(title, styles)
        story += _body_paragraphs(body, styles)

    # ── Valuation ─────────────────────────────────────────────────────────────
    val = ctx.get("valuation", {})
    if any(val.values()):
        story += _section_block("Valuation Summary", styles)
        val_data = [
            ["METRIC", "CURRENT", "5Y AVG / PEER AVG"],
            ["P/E (Forward)", f"{val.get('pe_forward','N/A')}x",
             f"{val.get('five_year_avg_pe','N/A')}x (5Y)"],
            ["EV / Revenue", f"{val.get('ev_revenue_ttm','N/A')}x", "—"],
            ["EV / EBITDA", f"{val.get('ev_ebitda_ttm','N/A')}x",
             f"{val.get('peer_avg_pe_forward','N/A')}x (peers)"],
        ]
        val_style = TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), ACCENT),
            ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8.5),
            ("ALIGN", (1, 0), (-1, -1), "CENTER"),
            ("ALIGN", (0, 0), (0, -1), "LEFT"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, LIGHT_GRAY]),
            ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#D0D5DC")),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ])
        val_table = Table(val_data, colWidths=[doc.width * 0.4, doc.width * 0.3, doc.width * 0.3])
        val_table.setStyle(val_style)
        story.append(val_table)

    # ── Disclaimer ────────────────────────────────────────────────────────────
    story.append(Spacer(1, 16))
    story.append(HRFlowable(width="100%", thickness=0.5, color=MID_GRAY))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "This report was generated by AlphaFlow AI and is intended for informational purposes only. "
        "It does not constitute financial advice, investment recommendations, or solicitation to buy or sell securities. "
        "Past performance is not indicative of future results. All financial data is sourced from public filings. "
        "AlphaFlow makes no representations as to the accuracy or completeness of this report.",
        styles["disclaimer"]
    ))

    doc.build(story)
    return buf.getvalue()
